apiVersion: v1
kind: Namespace
metadata:
  name: k8s-node-watcher-example
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-node-watcher-example
  namespace: k8s-node-watcher-example
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: k8s-node-watcher-example
  name: k8s-node-watcher-example
  labels:
    app: k8s-node-watcher-example
spec:
  selector:
    matchLabels:
      app: k8s-node-watcher-example
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-node-watcher-example
    spec:
      serviceAccount: k8s-node-watcher-example
      containers:
        - name: main
          imagePullPolicy: Always
          image: notify17/k8s-node-watcher-example:0.0.1
          env:
            - name: N17_RAW_API_KEY
              value: "REPLACE_API_KEY"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-node-watcher-example
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: k8s-node-watcher-example
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: k8s-node-watcher-example
subjects:
  - kind: ServiceAccount
    name: k8s-node-watcher-example
    namespace: k8s-node-watcher-example
---